# Generated by Django 4.1.2 on 2022-10-13 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код купона')),
                ('valid_from', models.DateTimeField(verbose_name='Начало действия купона')),
                ('valid_to', models.DateTimeField(verbose_name='Окончание действия купона')),
                ('discount', models.IntegerField(help_text='В процентах', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Размер скидки')),
                ('active', models.BooleanField(verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
    ]
